spring:
  application:
    name: semana03

  datasource:
    url: jdbc:mysql://localhost:3306/db_semana03
    username: root
    password:

  jpa:
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: create-drop

server:
  port: 8090
